name: Test the plone.app.standardtiles code

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plone:
          - ["3.11", "6.0-dev"]
          - ["3.12", "6.1-dev"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Plone ${{ matrix.plone[1] }} with Python ${{ matrix.plone[0] }}
        id: setup
        uses: plone/setup-plone@v2.0.0
        with:
          python-version: ${{ matrix.plone[0] }}
          plone-version: ${{ matrix.plone[1] }}
          setuptools-version: "74.0.0"
      - name: Install package
        run: |
          make VENV=off install

      - name: Run Lint
        run: |
          make VENV=off lint

      - name: Run tests
        run: |
          make VENV=off test-ignore-warnings
